-1:
  - 停下
  - 停
  - 别动
  - 站住
  - 暂停
  - 停止

1:
  - 起立
  - 站起来
  - 立正
  - 起来
  - 站好
  - 起身

2:
  - 趴下
  - 卧倒
  - 趴下去
  - 趴好
  - 趴着
  - 趴低
3:
  - 前进
  - 向前走
  - 走一步
  - 往前
  - 前走
  - 往前走

4:
  - 后退
  - 向后走
  - 退一步
  - 往后
  - 倒退
  - 后走

5:
  - 向左转
  - 左转
  - 往左
  - 左拐
  - 左边转
  - 左转弯

6:
  - 向右转
  - 右转
  - 往右
  - 右拐
  - 右边转
  - 右转弯


7:
  - 快一点
  - 快些
  - 加速
  - 赶快
  - 快点
  - 快点走

8:
  - 慢一点
  - 慢些
  - 减速
  - 慢点
  - 慢点走

10:
  - 爱心
  - 比心
  - 小心心
  - 点赞
  - 打心
  - 给心心

11:
  - 扭身子
  - 扭一扭
  - 摇摇身子
  - 扭腰
  - 晃一晃
  - 扭动身体

12:
  - 太空步
  - 跳太空步
  - 模仿迈克尔杰克逊
  - 月球漫步
  - 来个太空步
  - 酷炫走路

13:
  - 扭身跳
  - 扭跳
  - 扭腰跳

16:
  - 挥手
  - 摆手
  - 举手
  - 挥动
  - 打招呼
  - 示意
  - 招呼
  - 致意
  - 挥一挥手
  - 摆摆手
  - 挥动手臂
  - 打手势
  - 握手
  - 握个手
  - 伸手
  - 打招呼
  - 握爪
  - 给手

17:
  - 向前跳
  - 跳一下
  - 往前跳
  - 跳过去
  - 跳一跳
  - 蹦一下

18:
  - 鼓掌
  - 拍掌
  - 击掌
  - 喝彩
  - 叫好

19:
  - 霹雳舞
  - 跳霹雳舞
  - 跳舞
  - 来一段舞蹈
  - 跳个舞
  - 酷炫舞步

