西门:
  lat: 34.21318
  lon: 108.966133
御苑门:
  lat: 34.21318
  lon: 108.966133
银桥飞瀑:
  lat: 34.213195
  lon: 108.967507
御宴宫:
  lat: 34.212328
  lon: 108.966597
晏然居:
  lat: 34.212328
  lon: 108.966597
御宴宫和园:
  lat: 34.212199
  lon: 108.966766
品春门:
  lat: 34.21221
  lon: 108.967072
澄怀楼:
  lat: 34.211461
  lon: 108.967061
玉箕堂:
  lat: 34.211363
  lon: 108.967877
曲江流饮:
  lat: 34.211784
  lon: 108.968311
凤鸣九天剧院:
  lat: 34.211325
  lon: 108.969046
元功门:
  lat: 34.213111
  lon: 108.96907
芙蓉六骏:
  lat: 34.213694
  lon: 108.967372
荷塘观鱼:
  lat: 34.214178
  lon: 108.967343
自凉亭:
  lat: 34.214845
  lon: 108.965449
儿童乐园区:
  lat: 34.214845
  lon: 108.965449
陆羽茶社:
  lat: 34.21605
  lon: 108.966286
紫云楼:
  lat: 34.214586
  lon: 108.96906
西游记铜雕:
  lat: 34.212811
  lon: 108.970371
赤金走龙:
  lat: 34.211991
  lon: 108.970106
长安码头:
  lat: 34.217008
  lon: 108.967751
三彩马:
  lat: 34.217081
  lon: 108.966697
杏园:
  lat: 34.217081
  lon: 108.966697
龙门及第:
  lat: 34.217081
  lon: 108.966697
曲江胡店:
  lat: 34.213617
  lon: 108.971313
佛手印:
  lat: 34.211798
  lon: 108.973056
大唐师表:
  lat: 34.211833
  lon: 108.971584
经幢:
  lat: 34.211851
  lon: 108.972187
茶话弄:
  lat: 34.214069
  lon: 108.972587
镜像柱:
  lat: 34.216196
  lon: 108.97252
紫气东来亭:
  lat: 34.21595
  lon: 108.973319
化妆柱:
  lat: 34.216267
  lon: 108.97182
仕女馆:
  lat: 34.217079
  lon: 108.97109
八人铜镜:
  lat: 34.216265
  lon: 108.9708
旗亭:
  lat: 34.217529
  lon: 108.9691
旗亭商店:
  lat: 34.217261
  lon: 108.969837
丽人行:
  lat: 34.217108
  lon: 108.968928
竹里馆:
  lat: 34.217775
  lon: 108.967786
春明门:
  lat: 34.217871
  lon: 108.966627
服务大楼:
  lat: 34.211208
  lon: 108.972745
