0:
  name: 西门
  lat: 34.213213
  lon: 108.966510
1:
  name: 御苑门
  lat: 34.213213
  lon: 108.966510
2:
  name: 银桥飞瀑
  lat: 34.213211
  lon: 108.967462
3:
  name: 芙蓉六骏
  lat: 34.213662 
  lon: 108.967446
4:
  name: 元功门
  lat: 34.213086
  lon: 108.969216
5:
  name: 西游记铜雕
  lat: 34.212859
  lon: 108.970405
6:
  name: 凤凰池
  lat: 34.213076
  lon: 108.969656
7:
  name: 肯德基
  lat: 34.214433
  lon: 108.970404
8:
  name: 唐诗峡
  lat: 34.213671 
  lon: 108.971241
9:
  name: 曲江胡店
  lat: 34.213505 
  lon: 108.971499
10:
  name: 观音壁
  lat: 34.213070
  lon: 108.972203
11:
  name: 佛手印
  lat: 34.211795
  lon: 108.973129
12:
  name: 紫云楼
  lat: 34.214582
  lon: 108.969015
13:
  name: 陆羽茶社
  lat: 34.215515
  lon: 108.965537
14:
  name: 三彩马
  lat: 34.217081
  lon: 108.966697
15:
  name: 长安码头
  lat: 34.216975
  lon: 108.966925
16:
  name: 杏园
  lat: 34.217081
  lon: 108.966697
17:
  name: 竹里馆
  lat: 34.217416
  lon: 108.967902
18:
  name: 赤金走龙
  lat: 34.211991
  lon: 108.970106
19:
  name: 旗亭
  lat: 34.217232
  lon: 108.969082
20:
  name: 丽人行
  lat: 34.217315 
  lon: 108.968772
21:
  name: 仕女馆
  lat: 34.217169
  lon: 108.971015
22:
  name: 镜像柱
  lat: 34.216311 
  lon: 108.972442
23:
  name: 化妆柱
  lat: 34.216267
  lon: 108.97182
24:
  name: 南门
  lat: 34.211630 
  lon: 108.972745
25:
  name: 办公区
  lat: 34.211630 
  lon: 108.972745
