0:
  name: 肯德基
  lat: 34.214146 
  lon: 108.970559  
1:
  name: 茶话弄
  lat: 34.213143
  lon: 108.972113
2:
  name: 茶话弄
  lat: 34.214008
  lon: 108.972613
3:
  name: 西门
  lat: 34.213213
  lon: 108.966510
4:
  name: 御苑门
  lat: 34.213213
  lon: 108.966510
5:
  name: 银桥飞瀑
  lat: 34.213193
  lon: 108.967145
6:
  name: 银桥飞瀑
  lat: 34.213311
  lon: 108.967467
7:
  name: 银桥飞瀑
  lat: 34.213032
  lon: 108.967515
8:
  name: 芙蓉六骏
  lat: 34.213662 
  lon: 108.967446
9:
  name: 元功门
  lat: 34.213079
  lon: 108.969465
10:
  name: 元功门
  lat: 34.213089
  lon: 108.968622
11:
  name: 西游记铜雕
  lat: 34.212859
  lon: 108.970405
12:
  name: 凤凰池
  lat: 34.213076
  lon: 108.969656
13:
  name: 唐诗峡
  lat: 34.213671 
  lon: 108.971241
14:
  name: 曲江胡店
  lat: 34.213505 
  lon: 108.971499
15:
  name: 观音壁
  lat: 34.213070
  lon: 108.972203
16:
  name: 佛手印
  lat: 34.211795
  lon: 108.973129
17:
  name: 紫云楼
  lat: 34.214559
  lon: 108.969574
18:
  name: 紫云楼
  lat: 34.214532
  lon: 108.968582  
19:
  name: 陆羽茶社
  lat: 34.215515
  lon: 108.965537
20:
  name: 三彩马
  lat: 34.217081
  lon: 108.966697
21:
  name: 长安码头
  lat: 34.216975
  lon: 108.966925
22:
  name: 杏园
  lat: 34.217081
  lon: 108.966697
23:
  name: 竹里馆
  lat: 34.217416
  lon: 108.967902
24:
  name: 赤金走龙
  lat: 34.211991
  lon: 108.970106
25:
  name: 旗亭
  lat: 34.217232
  lon: 108.969082
26:
  name: 丽人行
  lat: 34.217315 
  lon: 108.968772
27:
  name: 仕女馆
  lat: 34.217169
  lon: 108.971015
28:
  name: 镜像柱
  lat: 34.216311 
  lon: 108.972442
29:
  name: 化妆柱
  lat: 34.216267
  lon: 108.97182
30:
  name: 南门
  lat: 34.211630 
  lon: 108.972745
31:
  name: 办公区
  lat: 34.211630 
  lon: 108.972745
