places:
  - 西门
  - 御苑门
  - 自凉亭
  - 陆羽茶社
  - 三彩马
  - 杏园
  - 龙门及第
  - 长安码头
  - 春明门
  - 竹里馆
  - 丽人行
  - 旗亭
  - 旗亭商店
  - 仕女馆
  - 八人铜镜
  - 镜像柱
  - 化妆柱
  - 东门
  - 紫气东来亭
  - 茶话弄
  - 曲江胡店
  - 西游记铜雕
  - 赤金走龙
  - 大唐师表
  - 经幢
  - 佛手印
  - 凤鸣九天剧院
  - 元功门
  - 曲江流饮
  - 玉箕堂
  - 澄怀楼
  - 品春门
  - 御宴宫和园
  - 御宴宫
  - 晏然居
  - 银桥飞瀑
  - 芙蓉六骏
  - 紫云楼

